[build]
  command = "chmod +x download-data.sh && ./download-data.sh 1 && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200